### ISSUE TITLE
There are some confusion about the architecture in your paper

### ISSUE THREAD

**Issue by Hshihua** [zhangqianhui/Sparsely-Grouped-GAN#1]
![sg-gan](https://user-images.githubusercontent.com/36783415/44889700-a804d500-ad09-11e8-89ab-99ec98263d21.png)

Why the input shape of bottleneck part is not equal to the output shape of encoder part, as well as the output shape of bottleneck part is not equal to the input shape of decoder part. Is my misunderstanding or your mistake, or something else that I miss?

**Comment by zhangqianhui** [comment]
You are right. Thanks.
