### ISSUE TITLE
about the datasets which is processed

### ISSUE THREAD

**Issue by EntaiY** [zhangqianhui/Sparsely-Grouped-GAN#2]
I wonder if you can updata the links of celebA datasets ?
The original link failed and i can not open it now . 
I would appreciate it if you had time to send it to me！！thanks！！
My mailbox is yinentai@126.com

**Comment by zhangqianhui** [comment]
https://drive.google.com/drive/folders/0B7EVK8r0v71pWEZsZE9oNnFzTm8
